### ISSUE TITLE
compile_to_image with YOLOv5 failed

### ISSUE THREAD

**Issue by yasuhiroitoTT** [tenstorrent/tt-buda-demos#119]
**Describe the bug**
YoloV5 model returns  exception while compiling model to tti file. 
The compilation was successfully ran when I added additional model execution with dummy data on CPU 
before wrapping the model by pybuda module. 

**To Reproduce**
1. install tt-buda v0.18.2 for grayskull
2. run attached reproducer by python3 repro.py
3. compilation failed with error message like screenshot
4. run again with option (by python3 repro.py --add_dummy) , then compilation was completed
    this option adds these lines
```
        with torch.no_grad():
            o=model(torch.randn(1,3,pixel_size,pixel_size))
```

[repro.py.zip](https://github.com/user-attachments/files/16529670/repro.py.zip)
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/731f3cb9-9a8d-492f-8968-b23c528ef1cc">

**Expected behavior**
This model should be compiled without adding dummy execution. 
Other models such as resnet50 included in our model demo did not need that additional step. 

**Screenshots**

**System (please complete the following information):**
 - Device: Single E150 
 - Host information: [e.g. Intel Xeon]
 - OS: Ubuntu 20.04LTS:
 - Version: tt-buda v0.18.2 for grayskull
 - Other relevant information: Python 3.8.10, firmware 80.10.0.0

**Additional context**

**Comment by milank94** [comment]
Hi @yasuhiroitoTT has this issue been resolved now with the additional config?
