### ISSUE TITLE
[$$ BOUNTY] Add Gemma 2B Model to TT-Buda Model Demos

### ISSUE THREAD

**Issue by Shubhamsaboo** [tenstorrent/tt-buda-demos#22]
### **Background:**
TT-Buda, developed by Tenstorrent, is a growing collection of model demos showcasing the capabilities of AI models running on Tenstorrent hardware. These demonstrations cover a wide range of applications, aiming to provide insights and inspiration for developers and researchers interested in advanced AI implementations.

### **Bounty Objective:**
We are excited to announce a bounty for contributing a new AI model demonstration to the TT-Buda repository. This is an opportunity for AI enthusiasts, researchers, and developers to showcase their skills, contribute to cutting-edge AI research, and earn rewards.

### Task Details: 

Integrate [**Gemma 2B**](https://huggingface.co/google/gemma-2b) into the TT-Buda demonstrations.

#### **Requirements:**

- The submission must include a comprehensive README.md detailing the model's architecture, implementation details, and usage instructions.
- The model should be fully functional and tested on Tenstorrent hardware, ensuring compatibility and performance optimization.
- Include sample inputs and outputs, demonstrating the model's capabilities.
- Provide documentation on any dependencies and installation procedures.

#### **Contribution Guidelines:**

- Fork the [TT-Buda model demos repository](https://github.com/tenstorrent/tt-buda-demos/tree/main/model_demos).
- Create a new directory within the `model_demos` folder following the naming convention: `model_yourModelName`.
- Ensure your code adheres to the coding standards and guidelines provided in the repository's `CONTRIBUTING.md` file.
- Submit a pull request with a detailed description of your model and any relevant information that will help reviewers understand and evaluate your contribution.

#### **Evaluation Criteria:**

- Innovation and Relevance: How does the model contribute new ideas or solutions? Is it relevant to current challenges in AI?
- Implementation Quality: Code readability, structure, and adherence to best practices.
- Performance: Efficiency and performance on Tenstorrent hardware.
- Documentation: Clarity and completeness of the accompanying documentation.

#### **Rewards:**
Contributions will be evaluated by the Tenstorrent team, and the best contribution will be eligible for $500 cash bounty. 

#### Get Started with Grayskull DevKit
Dive into AI development with the Grayskull DevKit, your gateway to exploring Tenstorrent's hardware. Paired with TT-Buda and TT-Metalium software approaches, it offers a solid foundation for AI experimentation. Secure your kit [here](https://tenstorrent.com/cards/?utm_source=bounty&utm_medium=github&utm_campaign=GS).

#### Connect on Discord
Join our [Discord](https://discord.gg/tenstorrent) to talk AI, share your journey, and get support from the Tenstorrent community and team. **Let's innovate together!**

**Comment by JonathanALevine** [comment]
I am working on this. And I feel I am very close to a solution!

Two bugs that I am working out:

(1) Model won't compile on grayskull
(2) transformers.pipelines.text_generation.postprocess is not outputting the generated text properly.

**Comment by Shubhamsaboo** [comment]
Assigned to @JonathanALevine

**Comment by Shubhamsaboo** [comment]
Any updates on this @JonathanALevine?

**Comment by Shubhamsaboo** [comment]
Great, please file any bugs or issues you encounter at the respective software repository. 
TT-Buda: https://github.com/tenstorrent/tt-buda/issues
TT-Metalium: https://github.com/tenstorrent-metal/tt-metal/issues

Happy to support our community, all the best for getting the bounty!

**Comment by Shubhamsaboo** [comment]
@JonathanALevine @JushBJJ @marty1885 have locked in their submission. Not accepting any more submissions for this bounty. Thank you for the contribution.
