### ISSUE TITLE
yolov3_holli_1x1.py is not work.

### ISSUE THREAD

**Issue by refill** [tenstorrent/tt-buda-demos#46]
**Describe the bug**

pytorch_yolov3_holli_1x1.py is not work.

(python_env) dn-dev@grayskull-dev:~/tt-buda-demos/model_demos$ python3 ./cv_demos/yolo_v3/pytorch_yolov3_holli_1x1.py
Traceback (most recent call last):
  File "/home/dn-dev/tt-buda-demos/model_demos/./cv_demos/yolo_v3/pytorch_yolov3_holli_1x1.py", line 9, in <module>
    from cv_demos.yolo_v3.holli_src.yolov3 import *
  File "/home/dn-dev/tt-buda-demos/model_demos/cv_demos/yolo_v3/holli_src/yolov3.py", line 5, in <module>
    from .yolov3_base import *
  File "/home/dn-dev/tt-buda-demos/model_demos/cv_demos/yolo_v3/holli_src/yolov3_base.py", line 3, in <module>
    from collections import Iterable, OrderedDict, defaultdict
**ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)**

**Expected behavior**

**System (please complete the following information):**
 - Device:  E75
 - Host information: AMD Ryzen 5 7600
 - OS : 22.04
 - Version : v0.10.9.gs.240401-alpha

**Additional context**
 - python 3.10
 
The Iterable abstract class was removed from collections in Python 3.10. See the deprecation note in the 3.9 collections[ docs](https://docs.python.org/3.9/library/collections.html). In the section [Removed](https://docs.python.org/3/whatsnew/3.10.html#removed) of the 3.10 docs, the item

**Comment by milank94** [comment]
@refill fix for the `Iterable` import error will be patched in #47; however, YOLOv3 support is not guaranteed on alpha release `v0.10.9-alpha`. You can give it a try.

**Comment by refill-dn** [comment]
I checked code. 
It works.
Thanks @milank94
