### ISSUE TITLE
pytorch_falcon.py error

### ISSUE THREAD

**Issue by danindiana** [tenstorrent/tt-buda-demos#51]
**Describe the bug**

tt-buda-demos/model_demos/nlp_demos/falcon$ python3 pytorch_falcon.py 
Traceback (most recent call last):
  File "pytorch_falcon.py", line 6, in <module>
    from nlp_demos.falcon.utils.model import Falcon
ModuleNotFoundError: No module named 'nlp_demos'

 - Device: [e.g. E150]
 - OS [e.g. Ubuntu 20.04]
 - Version [e.g. v0.9.75]
 - Other relevant information
python3 --version
Python 3.8.10
![Screenshot_2024-04-16_05-48-06](https://github.com/tenstorrent/tt-buda-demos/assets/3030588/ac3b39e4-d73f-4075-8fdd-264f7d1c1165)

**Comment by milank94** [comment]
Hi @danindiana 

A few pointers to help out:

- This demo will only run on the N150 board and not on the E150
- The demo should be run from the `model_demos` directory
- Try using the `export PYTHONPATH=.` variable to correct the import error

**Comment by milank94** [comment]
Closing issue for now due to inactivity. @danindiana please re-open if the issue persists.
