### ISSUE TITLE
Run TT-Buda Demos in CI on Tenstorrent hardware

### ISSUE THREAD

**Issue by EwoutH** [tenstorrent/tt-buda-demos#60]
Currently the demos in this repo aren't run in an automated fashion, as far as publicly visible. This has a few   implications:
- It's unproven if the examples in the repo actually work as of right now
- Changes to the models by (external) contributors aren't systematically validated
- For (new) contributors, possibly without Tenstorrent hardware, it's harder to develop and test new models
- The current performance and performance regressions (either caused by changes in the models themselves or by hardware) aren't tracked in any way.

By running the demos in CI (on every change and/or on a schedule) and tracking some performance statistics, would help all these problems. It would also help sell the value and robustness of Tenstorrent hardware, by having multiple models run periodically and consistently on their hardware.

Further more, running these demos in CI for Tenstorrent firmware/drivers, could also help validate software changes in those. It's basically a form of integration testing for Tenstorrent hardware.

**Comment by milank94** [comment]
@staylorTT something we should add to the migration plan.

**Comment by staylorTT** [comment]
ACK, I will add this as data to the current proposal.

**Comment by EwoutH** [comment]
Thanks for working on this! I'm curious, do you have any more details or updates to share on this effort?

**Comment by staylorTT** [comment]
https://github.com/tenstorrent/tt-mlir as we develop out our new compiler we should natively get this support. We will not be implementing this for buda at this time.
